spring:
  application:
    name: simple-ai-agent
  threads.virtual.enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4.1-nano
          temperature: 0.2